// Curated subset of lucide-react icons offered in the rich text "Icon" inline block.
// Keep names in sync with the imports in Component.tsx.
export const iconOptions = [
  'Star',
  'Heart',
  'MapPin',
  'Home',
  'Building2',
  'Bed',
  'Bath',
  'Wifi',
  'Car',
  'Plane',
  'Ship',
  'Mountain',
  'TreePine',
  'Palmtree',
  'Waves',
  'Sun',
  'Moon',
  'Coffee',
  'UtensilsCrossed',
  'Wine',
  'Dumbbell',
  'ParkingCircle',
  'ShieldCheck',
  'Sparkles',
  'Users',
  'Calendar',
  'Clock',
  'Phone',
  'Mail',
  'Globe',
  'Camera',
  'Compass',
  'Award',
  'Gem',
  'Crown',
  'Key',
  'Lock',
  'CheckCircle2',
  'Check',
  'ArrowRight',
  'ChevronRight',
  'Info',
  'AlertCircle',
  'Flame',
  'Snowflake',
  'Leaf',
  'Umbrella',
  'Bike',
  'ConciergeBell',
  'Luggage',
  'Tv',
  'AirVent',
  'WashingMachine',
] as const

export type IconName = (typeof iconOptions)[number]
